development:
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  firebase_api_key: <%= ENV["FIREBASE_API_KEY"] %>
production:
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  firebase_api_key: <%= ENV["FIREBASE_API_KEY"] %>
